# Generated by Django 5.2.5 on 2025-08-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
